package com.danchez.stori.ui.theme

import androidx.compose.ui.graphics.Color


val light_primary = Color(0xFF15393F)
val light_onPrimary = Color(0xFFFFFFFF)
val light_primaryContainer = Color(0xFF9cefff)
val light_onPrimaryContainer = Color(0xFF001f24)
val light_secondary = Color(0xFF006d3a)
val light_onSecondary = Color(0xFFFFFFFF)
val light_secondaryContainer = Color(0xFF8af9ae)
val light_onSecondaryContainer = Color(0xFF00210e)
val light_tertiary = Color(0xFF006d3a)
val light_onTertiary = Color(0xFFFFFFFF)
val light_tertiaryContainer = Color(0xFF8af9ae)
val light_onTertiaryContainer = Color(0xFF00210e)
val light_error = Color(0xFFba1a1a)
val light_onError = Color(0xFFffffff)
val light_errorContainer = Color(0xFFffdad6)
val light_onErrorContainer = Color(0xFF410002)
val light_background = Color(0xFFfbfcfd)
val light_onBackground = Color(0xFF191c1d)
val light_surface = Color(0xFFfbfcfd)
val light_onSurface = Color(0xFF191c1d)

val dark_primary = Color(0xFF006d3a)
val dark_onPrimary = Color(0xFF00363d)
val dark_primaryContainer = Color(0xFF004f58)
val dark_onPrimaryContainer = Color(0xFF9cefff)
val dark_secondary = Color(0xFF6ddc94)
val dark_onSecondary = Color(0xFF00391c)
val dark_secondaryContainer = Color(0xFF00522b)
val dark_onSecondaryContainer = Color(0xFF8af9ae)
val dark_tertiary = Color(0xFF6ddc94)
val dark_onTertiary = Color(0xFF00391c)
val dark_tertiaryContainer = Color(0xFF00522b)
val dark_onTertiaryContainer = Color(0xFF8af9ae)
val dark_error = Color(0xFFffb4ab)
val dark_onError = Color(0xFF690005)
val dark_errorContainer = Color(0xFF93000a)
val dark_onErrorContainer = Color(0xFFffdad6)
val dark_background = Color(0xFF191c1d)
val dark_onBackground = Color(0xFFe1e3e3)
val dark_surface = Color(0xFF191c1d)
val dark_onSurface = Color(0xFFe1e3e3)

val income_color = Color(0xFF059753)
val withdrawal_color = Color(0xFFba1a1a)
